"""initial

Revision ID: 72a228bee231
Revises: 
Create Date: 2025-02-08 14:43:16.586600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72a228bee231"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("longitude", sa.DECIMAL(), nullable=False),
        sa.Column("latitude", sa.DECIMAL(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city")
    # ### end Alembic commands ###
