"""initial

Revision ID: e20f94b59db8
Revises:
Create Date: 2025-02-09 16:39:26.698555

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e20f94b59db8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("outer_api_name", sa.String(), nullable=True),
        sa.Column("longitude", sa.DECIMAL(), nullable=False),
        sa.Column("latitude", sa.DECIMAL(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city")
    # ### end Alembic commands ###
